spring:
  application:
    name: hms
  datasource:
    url: jdbc:${DB_URL:mysql://localhost:3306/hms_db?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_EMAIL:your-email}
    password: ${MAIL_PASSWORD:app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
server:
  port: ${PORT:8080}
admin:
  email: ${ADMIN_EMAIL:admin@hms.com}
  password: ${ADMIN_PASSWORD:admin123}
jwt:
  secret: ${JWT_SECRET:gajsdhjagsdgadsgjtbqwytebqwtyqbtsddyuagsdgasdjhasdjgajsdgagsdjgasjdgjhasgdhgasdgqwenbsdoiqweoiquweqweqwe}
  expirytime: ${JWT_EXPIRY:86400000}
razorpay:
  key: ${RZRPY_KEY:rzp_test_RaPsJq0rZSFWD1}
  secret: ${RZRPY_SECRET:ZO0swacFGMgyE71JVvGuBOFP}